services:
  db:
    image: postgres:15-alpine
    container_name: task_db
    restart: always
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5499:5432"

  backend:
    build: ./backend
    container_name: django-backend # âœ… Nombre estandarizado
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=task_manager_db
      - DATABASE_USER=postgres_user
      - DATABASE_PASSWORD=postgres_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DEBUG=1
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://django-backend:8000
      - WATCHPACK_POLLING=true
      - HOSTNAME=0.0.0.0
    depends_on:
      - backend

volumes:
  postgres_data: